apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/quluqi/KubeVela-GitOps-Infra-Demo
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: main
      path: ./infrastructure
