apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: quluqi/core-mvc:v1.0.0
        port: 80
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              /: 80
